rethink helm hooks after testing the chart out

diff --git a/helm/kubeedge-cloudcore/templates/hook-jobs/patch-cilium-rbac.yaml b/helm/kubeedge-cloudcore/templates/hook-jobs/patch-cilium-rbac.yaml
--- a/helm/kubeedge-cloudcore/templates/hook-jobs/patch-cilium-rbac.yaml
+++ b/helm/kubeedge-cloudcore/templates/hook-jobs/patch-cilium-rbac.yaml
@@ -38,41 +38,65 @@ spec:
               set -o pipefail
               set -o nounset
               CILIUM_CLUSTERROLE=$(mktemp)
-              CILIUM_CLUSTERROLE_NEW=$(mktemp)
+              KUBEEDGE_CLUSTERROLE=$(mktemp)
               CILIUM_CLUSTERROLEBINDING=$(mktemp)
-              CILIUM_CLUSTERROLEBINDING_NEW=$(mktemp)
+              KUBEEDGE_CLUSTERROLEBINDING=$(mktemp)
 
+              # get the existing cilium clusterrole
               if ! kubectl get clusterrole cilium -o json >"${CILIUM_CLUSTERROLE}"; then
-                echo "[ERROR] Failed to retrieve Cilium ClusterRole."
+                echo "[ERROR] Failed to retrieve cilium clusterrole."
                 exit 1
               fi
 
-              if jq '(.rules[] | select((.apiGroups | index("cilium.io"))
+              # modify clusterrole for kubeedge and apply it
+              #
+              # this jq command does the following:
+              # - cleans up the role by removing status and some metadata fields
+              # - renames the role to "cilium-kubeedge"
+              # - adds "get" to the verbs of the rule that allows access to ciliumpodippools
+              #
+              if jq 'del(.status)
+                | del(.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"])
+                | del(.metadata.creationTimestamp, .metadata.resourceVersion, .metadata.uid)
+                | .metadata.name = "cilium-kubeedge"
+                | (.rules[] | select((.apiGroups | index("cilium.io"))
                   and (.resources | index("ciliumpodippools"))).verbs)
-                  |= (. + ["get"] | unique)' "${CILIUM_CLUSTERROLE}" > "${CILIUM_CLUSTERROLE_NEW}"; then
-                kubectl apply -f "${CILIUM_CLUSTERROLE_NEW}" || {
-                  echo "[ERROR] Failed to apply updated Cilium ClusterRole"
+                  |= (. + ["get"] | unique)' "${CILIUM_CLUSTERROLE}" > "${KUBEEDGE_CLUSTERROLE}"; then
+
+                kubectl apply -f "${KUBEEDGE_CLUSTERROLE}" || {
+                  echo "[ERROR] Failed to apply cilium-kubeedge clusterrole."
                   exit 1
                 }
               else
-                echo "[ERROR] Failed to update retrieved Cilium ClusterRole with jq."
+                echo "[ERROR] Failed to modify cilium clusterrole with jq."
                 exit 1
               fi
 
+              # get the existing cilium clusterrolebinding
               if ! kubectl get clusterrolebinding cilium -o json > "${CILIUM_CLUSTERROLEBINDING}"; then
-                echo "[ERROR] Failed to retrieve Cilium ClusterRoleBinding."
+                echo "[ERROR] Failed to retrieve cilium clusterrolebinding."
                 exit 1
               fi
 
-              if jq '.subjects = ((.subjects // []) + [
-                  {"kind": "ServiceAccount", "name": "cloudcore", "namespace": "{{ .Release.Namespace }}"},
-                  {"kind": "ServiceAccount", "name": "cloudcore", "namespace": "default"}
-                ])' "${CILIUM_CLUSTERROLEBINDING}" > "${CILIUM_CLUSTERROLEBINDING_NEW}"; then
-                kubectl apply -f "${CILIUM_CLUSTERROLEBINDING_NEW}" || {
-                  echo "[ERROR] Failed to apply updated Cilium ClusterRoleBinding."
+              # modify clusterrolebinding for kubeedge and apply it
+              #
+              # this jq command does the following:
+              # - cleans up the clusterolebinding by removing status and some metadata fields
+              # - renames the clusterrolebinding to "cilium-kubeedge"
+              # - replaces the subjects with the cloudcore serviceaccount in both the kubeedge and default namespaces
+              #
+              if jq 'del(.status)
+                | del(.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"])
+                | del(.metadata.creationTimestamp, .metadata.resourceVersion, .metadata.uid)
+                | .metadata.name = "cilium-kubeedge"
+                | .subjects = [{"kind": "ServiceAccount", "name": "cloudcore", "namespace": "{{ .Release.Namespace }}"},
+                  {"kind": "ServiceAccount", "name": "cloudcore", "namespace": "default"}]' "${CILIUM_CLUSTERROLEBINDING}" > "${KUBEEDGE_CLUSTERROLEBINDING}"; then
+
+                kubectl apply -f "${KUBEEDGE_CLUSTERROLEBINDING}" || {
+                  echo "[ERROR] Failed to apply cilium-kubeedge clusterrolebinding."
                   exit 1
                 }
               else
-                echo "[ERROR] Failed to update retrieved Cilium ClusterRoleBinding with jq."
+                echo "[ERROR] Failed to update retrieved cilium clusterrolebinding with jq."
                 exit 1
               fi
